document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\"stylesheet\" href=\"../css/style.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <script src=\"js/main.js\"></script>");
document.writeln("    <header>");
document.writeln("        <div class=\"header-banner\">");
document.writeln("        </div>");
document.writeln("        <nav>");
document.writeln("            <div class=\"site-title\">Apartment Sunset</div>");
document.writeln("            <ul>");
document.writeln("                <li><a href=\"#home\">Home</a></li>");
document.writeln("                <li><a href=\"#about\">About Us</a></li>");
document.writeln("                <li><a href=\"#contactus\">Contact</a></li>");
document.writeln("            <ul>");
document.writeln("        </nav>");
document.writeln("    </header>");
document.writeln("");
document.writeln("    <main class=\"wrapper\">");
document.writeln("        <div class=\"overlay\"></div>");
document.writeln("        <h1 class=\"heading\">Welcome to Apartment Sunset</h1>");
document.writeln("        ");
document.writeln("        <div class=\"content\">");
document.writeln("            <p><h5/<a id=\"about\">The property is an 8-minute walk from the beach. Apartment Sunset has a balcony with sea views, a garden and a terrace.</p>");
document.writeln("            <p>Here you are staying in Makarska, close to Makarska Bus Station and less than 1 km from St. Mark\'s Cathedral.</p>");
document.writeln("            The air-conditioned accommodation is 1.3 km from Ratac Beach, and guests benefit from private parking available on site and free WiFi.");
document.writeln("");
document.writeln("            The apartment has 2 bedrooms, 1 bathroom, a flat-screen TV with satellite channels, a dining area, a fully equipped kitchen, and a patio with garden views.");
document.writeln("");
document.writeln("            Popular points of interest nearby include Makarska Main Square, Sveti Petar Lighthouse and Makarska Harbour. </p>");
document.writeln("            <p>The nearest airport is Brac Airport, 28 km from Apartment Sunset.</h5><a>");
document.writeln("            <p><a href=\"https://www.booking.com/hotel/hr/apartment-sunset-makarska1.sv.html?activeTab=main\">Click here to make a reservation today on Booking.com</a></p>");
document.writeln("         </div>");
document.writeln("     </section>");
document.writeln("     ");
document.writeln("        <div class=\"container\">");
document.writeln("            <h1 class=\"heading\">With a unique view of the Adriatic Sea <span> and the mountain Biokovo</span></h1>");
document.writeln("                <div class=\"picture\">");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./66744939.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./66744825.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./sunset3.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./sunset5.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./66745051.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./66745509.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./66745593.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                    <img class=\"picture-image\" src=\"./sunset.jpg\"></div>");
document.writeln("");
document.writeln("                    <div class=\"picture-item\">");
document.writeln("                        <img class=\"picture-image\" src=\"./sunset6.jpg\"></div>");
document.writeln("");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </section>");
document.writeln("        <div class=\"map-container\">");
document.writeln("        <h1 class=\"heading\">Where Can You Find Us...</h1>");
document.writeln("        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2903.953541540495!2d17.0219952!3d43.2942946!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x134aee6f059ed99f%3A0x58f4e710837cdeb7!2sPut%20Makra%202B%2C%2021300%2C%20Makarska!5e0!3m2!1ssv!2shr!4v1660700965650!5m2!1ssv!2shr\" width=\"800\" height=\"600\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>");
document.writeln("      </div>");
document.writeln("    </section>");
document.writeln("  </main>");
document.writeln("");
document.writeln("  <h5/<a id=\"contactus\"></h5></a>");
document.writeln("  <div class=\"contactus\" id=\"contactus\">");
document.writeln("    <h1 class=\"heading\">Contact Us</h1>");
document.writeln("    <div class=\"btn-contact text-center\">");
document.writeln("        <a class=\"btn btn-default btn-contact\" href=\"andrea.simic@hotmail.com\" role=\"button\">CONTACT ME <span class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></span></a>");
document.writeln("      </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    ");
document.writeln("</body>");
document.writeln("</html>");